apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitproducer
spec:
  selector:
    matchLabels:
      app: myrabbitproducer
  template:
    metadata:
      labels:
        app: myrabbitproducer
    spec:
      containers:
      - name: myrabbitproducer
        image: jerry/credentialvalidation:1.0
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: myrabbitproducer
spec:
  type: NodePort
  selector:
    app: myrabbitproducer
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31500
